# Requirements:
# A build on Linux
# A build on Mac
# Package into a tarball
# Install with latest version, check "powershell -version"
# Install with requested older version, check "powershell -version"
# Preinstall powershell (or a fake powershell binary), install with latest version, make sure it skips installation but exposed powershell on path
# Preinstall powershell (or a fake powershell binary), install with requested older version, make sure it skips installation but exposed powershell on path

# Matrix:
# os: linux, mac
# requested version: latest, beta7
# fake powershell is preinstalled: true, false

sudo: false
language: node_js
node_js:
  - "10"
# matrix:
#     - os: windows
#     - os: linux
#     - os: mac
jobs:
  include:
    - stage: test
      os: windows
      script:
        - powershell -executionpolicy remotesigned -noprofile ./.travis/test-windows.ps1
    - stage: test
      os: mac
      script:
        - ./.travis/test-linux.sh
    - stage: test
      os: linux
      script:
        - ./.travis/test-linux.sh
